# Generated by Django 4.2.2 on 2023-06-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_txt',
            field=models.CharField(max_length=200, verbose_name='Question Text'),
        ),
    ]
